services:
  main:
    container_name: mahjong-website
    build: .
    ports:
      - "3000:3000"  # Make the website accessible at localhost:3000
    env_file:
      - .env  # Load environment variables
