services:
  main:
    container_name: mahjong-website
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    command: sh -c "npm ci && npm run dev"
